//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 06:45:39 PM EEST 
//


package com.ericsson.iptv.iap.cai3g.iptv_provisioning_equipment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.iptv.iap.cai3g.iptv_provisioning_equipment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.iptv.iap.cai3g.iptv_provisioning_equipment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetEquipmentCommonDataType }
     * 
     */
    public SetEquipmentCommonDataType createSetEquipmentCommonDataType() {
        return new SetEquipmentCommonDataType();
    }

    /**
     * Create an instance of {@link GetResponseEquipment }
     * 
     */
    public GetResponseEquipment createGetResponseEquipment() {
        return new GetResponseEquipment();
    }

    /**
     * Create an instance of {@link CreateGetEquipmentCommonDataType }
     * 
     */
    public CreateGetEquipmentCommonDataType createCreateGetEquipmentCommonDataType() {
        return new CreateGetEquipmentCommonDataType();
    }

    /**
     * Create an instance of {@link CreateEquipment }
     * 
     */
    public CreateEquipment createCreateEquipment() {
        return new CreateEquipment();
    }

    /**
     * Create an instance of {@link SetEquipment }
     * 
     */
    public SetEquipment createSetEquipment() {
        return new SetEquipment();
    }

}
