//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 06:45:39 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cai3g.iap.iptv.ericsson.com/iptv_provisioning_equipment/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericsson.iptv.iap.cai3g.iptv_provisioning_equipment;
