//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 06:45:39 PM EEST 
//


package com.ericsson.iptv.iap.cai3g.iptv_provisioning_subscriber;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.iptv.iap.cai3g.iptv_provisioning_subscriber package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VodTypeRentalList_QNAME = new QName("", "rentalList");
    private final static QName _VodTypeAuthorizationList_QNAME = new QName("", "authorizationList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.iptv.iap.cai3g.iptv_provisioning_subscriber
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NpvrType }
     * 
     */
    public NpvrType createNpvrType() {
        return new NpvrType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment.NoAuthentication }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment.NoAuthentication createBootstrapTypeBootstrapReserveIMSEquipmentNoAuthentication() {
        return new BootstrapType.BootstrapReserveIMSEquipment.NoAuthentication();
    }

    /**
     * Create an instance of {@link SetSubscriber }
     * 
     */
    public SetSubscriber createSetSubscriber() {
        return new SetSubscriber();
    }

    /**
     * Create an instance of {@link VodType.AuthorizationList }
     * 
     */
    public VodType.AuthorizationList createVodTypeAuthorizationList() {
        return new VodType.AuthorizationList();
    }

    /**
     * Create an instance of {@link WhatsOnTvType }
     * 
     */
    public WhatsOnTvType createWhatsOnTvType() {
        return new WhatsOnTvType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings createBootstrapTypeBootstrapReserveIMSEquipmentDeviceSettings() {
        return new BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings();
    }

    /**
     * Create an instance of {@link SubscriberPortalPreferencesType }
     * 
     */
    public SubscriberPortalPreferencesType createSubscriberPortalPreferencesType() {
        return new SubscriberPortalPreferencesType();
    }

    /**
     * Create an instance of {@link VodType.RentalList }
     * 
     */
    public VodType.RentalList createVodTypeRentalList() {
        return new VodType.RentalList();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.User }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.User createBootstrapTypeBootstrapReserveIMSEquipmentDeviceSettingsUser() {
        return new BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.User();
    }

    /**
     * Create an instance of {@link GetResponseSubscriber.Users }
     * 
     */
    public GetResponseSubscriber.Users createGetResponseSubscriberUsers() {
        return new GetResponseSubscriber.Users();
    }

    /**
     * Create an instance of {@link GetResponseSubscriber }
     * 
     */
    public GetResponseSubscriber createGetResponseSubscriber() {
        return new GetResponseSubscriber();
    }

    /**
     * Create an instance of {@link LocalTimeshiftType }
     * 
     */
    public LocalTimeshiftType createLocalTimeshiftType() {
        return new LocalTimeshiftType();
    }

    /**
     * Create an instance of {@link PayPerViewType.EventList }
     * 
     */
    public PayPerViewType.EventList createPayPerViewTypeEventList() {
        return new PayPerViewType.EventList();
    }

    /**
     * Create an instance of {@link RemoteAuthorizationType }
     * 
     */
    public RemoteAuthorizationType createRemoteAuthorizationType() {
        return new RemoteAuthorizationType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReservePlainEquipment }
     * 
     */
    public BootstrapType.BootstrapReservePlainEquipment createBootstrapTypeBootstrapReservePlainEquipment() {
        return new BootstrapType.BootstrapReservePlainEquipment();
    }

    /**
     * Create an instance of {@link LpvrType }
     * 
     */
    public LpvrType createLpvrType() {
        return new LpvrType();
    }

    /**
     * Create an instance of {@link VodType.AuthorizationList.Svod }
     * 
     */
    public VodType.AuthorizationList.Svod createVodTypeAuthorizationListSvod() {
        return new VodType.AuthorizationList.Svod();
    }

    /**
     * Create an instance of {@link CreateSubscriber }
     * 
     */
    public CreateSubscriber createCreateSubscriber() {
        return new CreateSubscriber();
    }

    /**
     * Create an instance of {@link PayPerViewType.EventList.Event }
     * 
     */
    public PayPerViewType.EventList.Event createPayPerViewTypeEventListEvent() {
        return new PayPerViewType.EventList.Event();
    }

    /**
     * Create an instance of {@link SubscriberAccountIdentityType }
     * 
     */
    public SubscriberAccountIdentityType createSubscriberAccountIdentityType() {
        return new SubscriberAccountIdentityType();
    }

    /**
     * Create an instance of {@link VodType.RentalList.VodTitle }
     * 
     */
    public VodType.RentalList.VodTitle createVodTypeRentalListVodTitle() {
        return new VodType.RentalList.VodTitle();
    }

    /**
     * Create an instance of {@link ChannelManagerType.ChannelPackageList.ChannelPackage }
     * 
     */
    public ChannelManagerType.ChannelPackageList.ChannelPackage createChannelManagerTypeChannelPackageListChannelPackage() {
        return new ChannelManagerType.ChannelPackageList.ChannelPackage();
    }

    /**
     * Create an instance of {@link BootstrapType }
     * 
     */
    public BootstrapType createBootstrapType() {
        return new BootstrapType();
    }

    /**
     * Create an instance of {@link SubscriberServicesType }
     * 
     */
    public SubscriberServicesType createSubscriberServicesType() {
        return new SubscriberServicesType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.Subscriber }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.Subscriber createBootstrapTypeBootstrapReserveIMSEquipmentDeviceSettingsSubscriber() {
        return new BootstrapType.BootstrapReserveIMSEquipment.DeviceSettings.Subscriber();
    }

    /**
     * Create an instance of {@link BroadcastReminderType }
     * 
     */
    public BroadcastReminderType createBroadcastReminderType() {
        return new BroadcastReminderType();
    }

    /**
     * Create an instance of {@link PortalSelectorType }
     * 
     */
    public PortalSelectorType createPortalSelectorType() {
        return new PortalSelectorType();
    }

    /**
     * Create an instance of {@link PayPerViewType.BlockList }
     * 
     */
    public PayPerViewType.BlockList createPayPerViewTypeBlockList() {
        return new PayPerViewType.BlockList();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReservePlainEquipment.NoAuthentication }
     * 
     */
    public BootstrapType.BootstrapReservePlainEquipment.NoAuthentication createBootstrapTypeBootstrapReservePlainEquipmentNoAuthentication() {
        return new BootstrapType.BootstrapReservePlainEquipment.NoAuthentication();
    }

    /**
     * Create an instance of {@link PayPerViewType.BlockList.Block }
     * 
     */
    public PayPerViewType.BlockList.Block createPayPerViewTypeBlockListBlock() {
        return new PayPerViewType.BlockList.Block();
    }

    /**
     * Create an instance of {@link PayPerViewType }
     * 
     */
    public PayPerViewType createPayPerViewType() {
        return new PayPerViewType();
    }

    /**
     * Create an instance of {@link VodType }
     * 
     */
    public VodType createVodType() {
        return new VodType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReservePlainEquipment.DeviceSettings.Authentication }
     * 
     */
    public BootstrapType.BootstrapReservePlainEquipment.DeviceSettings.Authentication createBootstrapTypeBootstrapReservePlainEquipmentDeviceSettingsAuthentication() {
        return new BootstrapType.BootstrapReservePlainEquipment.DeviceSettings.Authentication();
    }

    /**
     * Create an instance of {@link GetSubscriberCommonDataType }
     * 
     */
    public GetSubscriberCommonDataType createGetSubscriberCommonDataType() {
        return new GetSubscriberCommonDataType();
    }

    /**
     * Create an instance of {@link ChannelManagerType.ChannelList.Channel }
     * 
     */
    public ChannelManagerType.ChannelList.Channel createChannelManagerTypeChannelListChannel() {
        return new ChannelManagerType.ChannelList.Channel();
    }

    /**
     * Create an instance of {@link IptvProxyType }
     * 
     */
    public IptvProxyType createIptvProxyType() {
        return new IptvProxyType();
    }

    /**
     * Create an instance of {@link ReservedUsersType.ReservedUser }
     * 
     */
    public ReservedUsersType.ReservedUser createReservedUsersTypeReservedUser() {
        return new ReservedUsersType.ReservedUser();
    }

    /**
     * Create an instance of {@link ChannelManagerType.ChannelPackageList }
     * 
     */
    public ChannelManagerType.ChannelPackageList createChannelManagerTypeChannelPackageList() {
        return new ChannelManagerType.ChannelPackageList();
    }

    /**
     * Create an instance of {@link ChannelManagerType }
     * 
     */
    public ChannelManagerType createChannelManagerType() {
        return new ChannelManagerType();
    }

    /**
     * Create an instance of {@link BlockedStateType }
     * 
     */
    public BlockedStateType createBlockedStateType() {
        return new BlockedStateType();
    }

    /**
     * Create an instance of {@link CreateSubscriberCommonDataType }
     * 
     */
    public CreateSubscriberCommonDataType createCreateSubscriberCommonDataType() {
        return new CreateSubscriberCommonDataType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment.SimplePasswordAuthentication }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment.SimplePasswordAuthentication createBootstrapTypeBootstrapReserveIMSEquipmentSimplePasswordAuthentication() {
        return new BootstrapType.BootstrapReserveIMSEquipment.SimplePasswordAuthentication();
    }

    /**
     * Create an instance of {@link ReservedUsersType }
     * 
     */
    public ReservedUsersType createReservedUsersType() {
        return new ReservedUsersType();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReserveIMSEquipment }
     * 
     */
    public BootstrapType.BootstrapReserveIMSEquipment createBootstrapTypeBootstrapReserveIMSEquipment() {
        return new BootstrapType.BootstrapReserveIMSEquipment();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReservePlainEquipment.SimplePasswordAuthentication }
     * 
     */
    public BootstrapType.BootstrapReservePlainEquipment.SimplePasswordAuthentication createBootstrapTypeBootstrapReservePlainEquipmentSimplePasswordAuthentication() {
        return new BootstrapType.BootstrapReservePlainEquipment.SimplePasswordAuthentication();
    }

    /**
     * Create an instance of {@link BootstrapType.BootstrapReservePlainEquipment.DeviceSettings }
     * 
     */
    public BootstrapType.BootstrapReservePlainEquipment.DeviceSettings createBootstrapTypeBootstrapReservePlainEquipmentDeviceSettings() {
        return new BootstrapType.BootstrapReservePlainEquipment.DeviceSettings();
    }

    /**
     * Create an instance of {@link ChannelManagerType.ChannelList }
     * 
     */
    public ChannelManagerType.ChannelList createChannelManagerTypeChannelList() {
        return new ChannelManagerType.ChannelList();
    }

    /**
     * Create an instance of {@link SubscriberPortalPreferencesType.Preference }
     * 
     */
    public SubscriberPortalPreferencesType.Preference createSubscriberPortalPreferencesTypePreference() {
        return new SubscriberPortalPreferencesType.Preference();
    }

    /**
     * Create an instance of {@link Blocked }
     * 
     */
    public Blocked createBlocked() {
        return new Blocked();
    }

    /**
     * Create an instance of {@link SetSubscriberCommonDataType }
     * 
     */
    public SetSubscriberCommonDataType createSetSubscriberCommonDataType() {
        return new SetSubscriberCommonDataType();
    }

    /**
     * Create an instance of {@link CatchupTvType }
     * 
     */
    public CatchupTvType createCatchupTvType() {
        return new CatchupTvType();
    }

    /**
     * Create an instance of {@link GetResponseSubscriber.Equipment }
     * 
     */
    public GetResponseSubscriber.Equipment createGetResponseSubscriberEquipment() {
        return new GetResponseSubscriber.Equipment();
    }

    /**
     * Create an instance of {@link NetworkTimeshiftType }
     * 
     */
    public NetworkTimeshiftType createNetworkTimeshiftType() {
        return new NetworkTimeshiftType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VodType.RentalList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rentalList", scope = VodType.class)
    public JAXBElement<VodType.RentalList> createVodTypeRentalList(VodType.RentalList value) {
        return new JAXBElement<VodType.RentalList>(_VodTypeRentalList_QNAME, VodType.RentalList.class, VodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VodType.AuthorizationList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authorizationList", scope = VodType.class)
    public JAXBElement<VodType.AuthorizationList> createVodTypeAuthorizationList(VodType.AuthorizationList value) {
        return new JAXBElement<VodType.AuthorizationList>(_VodTypeAuthorizationList_QNAME, VodType.AuthorizationList.class, VodType.class, value);
    }

}
